### ISSUE TITLE
チャンネルをユーザー投稿一覧に表示しないようにする?

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#10]
## Summary

任意のチャンネル、または全てのチャンネルについて、ユーザーの投稿一覧から見えないようにする需要があるようです。

https://misskey.niri.la/notes/9hlanh5lw6
> 任意のチャンネルをプロフィールから表示したノートでも表示しないとかできれば良いんだけどね

https://misskey.niri.la/notes/9hlatvfjua
> 「クローラーをインデックスさせにゃい」をしてにゃいと、あまりに生々しい話をノートするとクローラーにノートが回収されてしまい場合によってはデジタルタトゥーににゃる恐れあり

**Comment by anatawa12** [comment]
チャンネルノートをnoindexしたほうが良かったりする? (できるか調査してないけど)

**Comment by Sayamame-beans** [comment]
あ〜、諸説ありますね…
しかし後者についてはそういうことになりますよね(チャンネルのNSFWがこの条件として適用出来ると最良ですが、未実装ですからね〜…)

**Comment by niwaniwa** [comment]
noindexは確かにしたいかも。
さやまめさんの言う通りNSFW実装の後かな...?

**Comment by anatawa12** [comment]
とりあえず実装の前提とかを見やすくするため関連issueリンクします
- misskey-dev#11270
  - #21
- misskey-dev#11376

**Comment by anatawa12** [comment]
~~#12 で実装したハイライトチャンネル除外もNSFWチャンネルに限定するのも悪くはなさそう。ただしjoin対象増えるので負荷に注意必要~~
別issue #20

**Comment by anatawa12** [comment]
これ、hide by defaultだとしてshow機能は(モデレーション的にも)ほしい気がするので切り替えどこに入れるかのUI意見募集〜

**Comment by Sayamame-beans** [comment]
設定/プライバシー ですかね～…?

**Comment by anatawa12** [comment]
見る側でオンオフを想定してるのでなんか違うかも？

**Comment by Sayamame-beans** [comment]
あー…
私は、見せる側(各ユーザーページの主側)が決めたいことだと思ってました

**Comment by anatawa12** [comment]
モデレーション的に必要そうだなぁというのと、公開投稿なので見る側のつもり

NSFWチャンネル投稿が見えてることの問題はCWが常に見えてるようなものだと認識してます

**Comment by Sayamame-beans** [comment]
> モデレーション的に必要

これよく分からない
特定ユーザーのチャンネル投稿を読むのにユーザーページから読めた方が良いだろうってことですかね?

後者、なるほど… それにhide by defaultだと非ログイン状態だとそこからは見れないわけですし、良さそう…?
であれば、設定/全般/ノートの表示 辺りですかね。ノートの表示の上(タイムラインに返信表示する項目の所)でも良いかもしれません

**Comment by anatawa12** [comment]
> 特定ユーザーのチャンネル投稿を読むのにユーザーページから読めた方が良いだろうってことですかね?

yes

> 設定/全般/ノートの表示 辺りですかね。ノートの表示の上(タイムラインに返信表示する項目の所)でも良いかもしれません

良さそう　thx

**Comment by anatawa12** [comment]
noindex分割: #34

**Comment by anatawa12** [comment]
よく考えたらcollapse by defaultにするのでいいのか？

**Comment by Sayamame-beans** [comment]
> よく考えたらcollapse by defaultにするのでいいのか？

No. 非ログイン状態でユーザーページから直接見えるのがあまり良くないと推察します。
> https://misskey.niri.la/notes/9hlatvfjua
> > 「クローラーをインデックスさせにゃい」をしてにゃいと、あまりに生々しい話をノートするとクローラーにノートが回収されてしまい場合によってはデジタルタトゥーににゃる恐れあり

**Comment by anatawa12** [comment]
インデックス問題は別途対処のつもり

**Comment by anatawa12** [comment]
インデックス問題は別途対処のつもりなので別で考えてください

**Comment by anatawa12** [comment]
ログイン済: collapse by default
ログインしてない: 非表示

がインデックス問題と考えた上でのちょうどいいくらいかなと思ってたりします

**Comment by Sayamame-beans** [comment]
> ログイン済: collapse by default
> ログインしてない: 非表示
> 
> がインデックス問題と考えた上でのちょうどいいくらいかなと思ってたりします

良いと思います。

**Comment by Sayamame-beans** [comment]
設定項目が見当たりません
> > 設定/全般/ノートの表示 辺りですかね。ノートの表示の上(タイムラインに返信表示する項目の所)でも良いかもしれません
> 
> 良さそう　thx
