### ISSUE TITLE
VRChat ワールドURLのプレビュー表示を改善

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#101]
### Summary

> ぶいちゃのワールドサムネがみすきーでも見えるようになればいいのになあ

https://misskey.niri.la/notes/9knln6o0mp

> TwitterでもDiscordでも表示されるな…つまり、:misskey:がプレビューする対象が良くない

https://misskey.niri.la/notes/9knlsesi9i

### Purpose

ワールドのサムネは見えた方が良い

時々動画がサムネ?になるケースがあると記憶していて、それはプレイヤーを直接開けた方が嬉しいとかあるのかもしれない(分からない)(こっちは優先度低)

**Comment by Sayamame-beans** [comment]
このissueに取り組む際、特別な対応(VRC固有の対応)を行わなくて良かった場合は本家にもcommit投げた方が良いかもしれない。

**Comment by KisaragiEffective** [comment]
例: SuRRoomだと

```sh
curl https://vrchat.com/home/world/wrld_beddab1e-fee1-cafe-f00d-ca7c0dd1eca7 \
  -H "User-Agent: KisaragiMarine/1.0; contact: https://github.com/KisaragiEffective"
```

から

```html
<!-- <head> -->
    <meta name="description" content="SuRroom by citrusxr - a virtual reality world on VRChat">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="VRChat">
<meta name="twitter:title" content="SuRroom by citrusxr">
<meta name="twitter:description" content="Experience true VR home world․ Multilingual supported․ created by ˸ CITRUS Studio members˸［＂Shatoo＂‚ ＂ureishi＂‚ ＂Rastvas＂‚ ＂Izzy_da＂］">
<meta name="twitter:creator" content="VRChat">
<meta name="twitter:image" content="https://api.vrchat.cloud/api/1/file/file_0043cc43-931c-4c4e-87a0-2e0e4622d320/3/file">
<meta name="twitter:image:alt" content="A preview image of VRChat world &quot;SuRroom&quot; by citrusxr">
<meta name="og:title" content="SuRroom by citrusxr">
<meta name="og:type" content="website">
<meta name="og:image" content="https://api.vrchat.cloud/api/1/file/file_0043cc43-931c-4c4e-87a0-2e0e4622d320/3/file">
<meta name="og:image:alt" content="A preview image of VRChat world &quot;SuRroom&quot; by citrusxr">
<meta name="og:description" content="Experience true VR home world․ Multilingual supported․ created by ˸ CITRUS Studio members˸［＂Shatoo＂‚ ＂ureishi＂‚ ＂Rastvas＂‚ ＂Izzy_da＂］">
<meta name="og:siteName" content="VRChat">
```

が返ってきます

**Comment by anatawa12** [comment]
https://misskey.niri.la/notes/9mkabmpwut

流れてきたlinkの最初を取ってる説がありそう。

**Comment by anatawa12** [comment]
related: https://github.com/syuilo/summaly

**Comment by anatawa12** [comment]
うーんOGPのmetaタグって`<meta property="og:image" content="">`が正しいので、VRChatのwebsiteのCanny書くのが正しそう。

https://ogp.me/

**Comment by anatawa12** [comment]
しかしsummalyがわもバグってるな。twitter card用の値は`<meta name="twitter:image" content="">`が正しいようだけど`property`でとってる

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary

>     		$('meta[property="twitter:image"]').attr('content') ||

https://github.com/syuilo/summaly/blob/b994e67281abc3faae53c888a232c84a4ea1a01d/src/general.ts#L30C1-L30C57

**Comment by anatawa12** [comment]
とりあえずtwitter card imageの話はissueにした syuilo/summaly#151

**Comment by anatawa12** [comment]
misskey-dev/summaly#14

npmにあるのは古いらしいので作り直した

**Comment by anatawa12** [comment]
https://feedback.vrchat.com/website/p/ogp-is-not-correct

**Comment by KisaragiEffective** [comment]
![tracked on canny](https://github.com/niri-la/misskey.niri.la/assets/48310258/5fdb1f43-e6e7-4269-bded-cb32ee58e959)

canny status: tracked

**Comment by anatawa12** [comment]
#122
