### ISSUE TITLE
チャンネル単位のミュート機能

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#11]
## Summary

RNとかで流れてこないように出来ると思います。
引用は…どうなんでしょうね(現状のミュートの仕様に沿う?)

**Comment by anatawa12** [comment]
upstreamに投げて良さそう

**Comment by Sayamame-beans** [comment]
既にありました。
https://github.com/misskey-dev/misskey/issues/10649

**Comment by Sayamame-beans** [comment]
triage: Close because this is completely in the area of upstream
