### ISSUE TITLE
Picks

### ISSUE THREAD

**Issue by anatawa12** [niwaniwa/misskey#110]

**Comment by anatawa12** [comment]
- https://github.com/misskey-dev/misskey/pull/12509

**Comment by anatawa12** [comment]
- https://github.com/misskey-dev/misskey/pull/12512

**Comment by anatawa12** [comment]
@meronmks ↓は一応完成というつもりで問題ないですかね？pickしちゃうのを検討してます
- https://github.com/misskey-dev/misskey/pull/12132 => #112

**Comment by anatawa12** [comment]
フロントのみだしいいや入れちゃう
- https://github.com/misskey-dev/misskey/pull/12437 => #113

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/pull/12507

これ入れる？

**Comment by Sayamame-beans** [comment]
12507は後のpickで支障出る可能性もありそうだし、一旦後回し(タイミング合わせる)が良さそう
