### ISSUE TITLE
ホーム化のモデレーションにモデログのタイプが設定されてないっぽい

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#118]
### 💡 概要

![image](https://github.com/niri-la/misskey.niri.la/assets/61457993/27cb59ae-af01-41ad-b915-ad80a9473214)
"ファイルをセンシティブ付与"のものを参考にすると良いかも
related: #78  

### 🥰 想定される挙動

`投稿をホーム投稿に変更: @ユーザーID`みたいな感じの表示がある

### 🤬 Actual Behavior

ない

### 💻 お使いの環境

```markdown
* 機種とOS:
* ブラウザ:
```

**Comment by anatawa12** [comment]
翻訳指定してないかも

**Comment by Sayamame-beans** [comment]
あ～

**Comment by anatawa12** [comment]
https://github.com/niri-la/misskey.niri.la/blob/0e711efae2a1124ddb5365e0d59f97e1486dced8/locales/ja-JP.yml#L2309-L2342

ここに追加すれば良さそう

**Comment by Sayamame-beans** [comment]
やろうと思ったんですけど、他にもいくつかやり零してそう…?
https://github.com/search?q=repo%3Aniri-la%2Fmisskey.niri.la%20markSensitiveDriveFile&type=code

**Comment by Sayamame-beans** [comment]
これ解決したら本家にも投げたいところですね(翻訳周りをハードコードしてたのを調整する必要があるのかな…?)
https://github.com/misskey-dev/misskey/issues/11435

**Comment by anatawa12** [comment]
CASCADE処理(RN等の処理)してないのupstreamに同判断されるだろうって感じはある

**Comment by anatawa12** [comment]
モデログ名の翻訳の話、私がやった方がいい？任せていい？

**Comment by Sayamame-beans** [comment]
どこまでやれば良いのかあんまり分かってなくて止めてます
適当で良ければやってみます

**Comment by anatawa12** [comment]
適当でいいよ

**Comment by Sayamame-beans** [comment]
> CASCADE処理(RN等の処理)してないのupstreamに同判断されるだろうって感じはある

引用とか考えると範囲が相当広くなり得るし、そこまでしないといけないかなぁという感じが…? (まあしても良いとは思うけれど)
というかあれですね、https://github.com/misskey-dev/misskey/issues/12757 とある意味似てるのでこれもノート編集の扱いになるのかな
