### ISSUE TITLE
Pawooをトレンドの算出から除外する？

### ISSUE THREAD

**Issue by KisaragiEffective** [niwaniwa/misskey#119]
### 概要

* 課題: トレンドにNSFWワードが来てしまうとNSFWガイドラインと整合性が取れない
  * 今日の事例: https://misskey.niri.la/notes/9n5tcshts2
* 事実: Pawooは何かとNSFWがち
* 制約: トレンドのモデレーションを都度することはリソースの消費となりよくない
* 制約: ホワイトリストやブラックリストの定義も同様の理由でよくない

### 目的

そこで、トレンド算出からはPawooのノートを除外することを提案します。それにより上にあげた制約を満たしながら事象を解決できると考えます。
しかし、これは統計的データによる裏付けを持たないため、実際に行うにはもう少しまともな追試が必要となるでしょう。

**Comment by Sayamame-beans** [comment]
Pawoo専用の除外を実装するよりは、https://github.com/misskey-dev/misskey/issues/12591 と https://github.com/misskey-dev/misskey/issues/11401 が効いてきそうです(どちらも未実装)(よく見たら後者はトレンドというよりただのハイライトしか考慮してなかった…)
とりあえず前者だけあれば解決しそうです
