### ISSUE TITLE
テキストをペーストしたときにdiscordみたいにテキストファイルにするかを訊く機能

### ISSUE THREAD

**Issue by anatawa12** [niwaniwa/misskey#130]
### 概要

テキストをペーストしたときにdiscordみたいにテキストファイルにするかを訊く機能

### 目的

https://misskey.niri.la/notes/9o74ho4osq
> ConsoleLogSaverの使い勝手考えると長いテキストをペーストしたときにdiscordみたいにテキストファイルにするかを訊く機能がMisskeyにもあったほうが便利そう

長いテキストを共有しやすくする

**Comment by Sayamame-beans** [comment]
本家に実装済み
