### ISSUE TITLE
メニューのところにNSFWガイドラインのリンク載せたい

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#137]
### 概要

タイトル通り

### 目的

アクセス経路の追加

**Comment by Sayamame-beans** [comment]
トップページ(登録前)のミートボール(多分)
https://github.com/niri-la/misskey.niri.la/blob/766f2ffd6e66af110b8c9bff164801d10986e108/packages/frontend/src/components/MkVisitorDashboard.vue#L92-L130

**Comment by Sayamame-beans** [comment]
インスタンス情報メニュー(通常)
https://github.com/niri-la/misskey.niri.la/blob/766f2ffd6e66af110b8c9bff164801d10986e108/packages/frontend/src/ui/_common_/common.ts#L43-L119

**Comment by anatawa12** [comment]
リンク先ってハードコード可能？

**Comment by Sayamame-beans** [comment]
出来る…はず(変わる可能性が無いわけではないのでUIどうしようかなぁと思っていた)

**Comment by Sayamame-beans** [comment]
一旦ハードコートにしてみようかなの気持ち

**Comment by anatawa12** [comment]
> 出来る…はず

ならUIどこにするかくらいかな

**Comment by Sayamame-beans** [comment]
変数の後ろにある`!`が何か分からないな…

**Comment by KisaragiEffective** [comment]
> @Sayamame-beans wrote:
> 変数の後ろにある`!`が何か分からないな…

これはTypeScriptの[non-null assertion](https://typescript-jp.gitbook.io/deep-dive/intro/strictnullchecks)です
