### ISSUE TITLE
[Priority-High] アカウントの削除に時間差を設ける、または削除を一時封印出来るようにする

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#138]
### 概要

> 荒らし等において、アカウントを作成して荒らした後、即座にアカウントを削除して逃げるケースが考えられる。 この場合、アカウントが消えることで情報がすべて失われてしまうため、削除に時間差を設けたい。

https://github.com/misskey-dev/misskey/issues/13303

### 目的

> 荒らし等への対処のため。 情報があったとして対処出来るかは分かりませんが、消えると対処のしようがありません。

**Comment by anatawa12** [comment]
論理削除化できるのかな。とりあえず今日中に調査して可能なら実装します。

@Sayamame-beans @niwaniwa 法的リスクがわからんのでそこらへんの調査はお願いしたい。よく言われるのはGDPRなのでないとは思いたいけど。

**Comment by anatawa12** [comment]
楽な実装案としてはモデログに追加するとかかな
