### ISSUE TITLE
登録用メールアドレスの条件を強化

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#145]
### 概要

登録に利用出来ないメールアドレスの辞書を強化しましょう
(何かそういうサービスがあった気がする)

### 目的

怪しい人が登録する可能性を減らします

**Comment by Sayamame-beans** [comment]
🧐  https://github.com/disposable-email-domains/disposable-email-domains

**Comment by Sayamame-beans** [comment]
👀 https://github.com/mattyatea/disposable-email-domains

**Comment by anatawa12** [comment]
現状 https://www.npmjs.com/package/deep-email-validator が使われてるっぽいけど https://github.com/mattyatea/disposable-email-domains / https://github.com/disposable-email-domains/disposable-email-domains のほうが更新されてるからそっちにしたほうがいいのか

**Comment by Sayamame-beans** [comment]
ぽい

**Comment by anatawa12** [comment]
ちなみに [verifymail.io](https://verifymail.io/) か [truemail](https://github.com/truemail-rb/truemail-rack) (since 2024.2.0) に問い合わせることが可能なので [disposable-email-domains](https://github.com/mattyatea/disposable-email-domains)(等)を使った truemailの実装があれば嬉しそう

**Comment by anatawa12** [comment]
まぁでもとりあえずdisposable-email-domainsのチェックをを追加しますかね

**Comment by anatawa12** [comment]
うーん... bannedEmailDomains に https://github.com/mattyatea/disposable-email-domains の中身を追加するだけでもいい気がしてきた

**Comment by anatawa12** [comment]
~~あーでもprefix判定しないといけないからだめ化~~

**Comment by anatawa12** [comment]
bannedEmailDomainsの判定ちゃんとサブドメインのチェック走るから問題なかった。

**Comment by Sayamame-beans** [comment]
disposable-email-domains、blacklistだけじゃなくてwhitelistあるっぽいんだけどどうなんだろうね(blacklist内容追加だけで良いのかな)

**Comment by anatawa12** [comment]
> The file [allowlist.conf](https://github.com/mattyatea/disposable-email-domains/blob/master/allowlist.conf) gathers email domains that are **often** identified as disposable but in fact are not.

> The shell script will help you convert uppercase to lowercase, sort, remove duplicates and remove allowlisted domains.

なのでallowlistはブラックリストに含まれてないです

**Comment by Sayamame-beans** [comment]
> > The file [allowlist.conf](https://github.com/mattyatea/disposable-email-domains/blob/master/allowlist.conf) gathers email domains that are **often** identified as disposable but in fact are not.
> 
> > The shell script will help you convert uppercase to lowercase, sort, remove duplicates and remove allowlisted domains.
> 
> なのでallowlistはブラックリストに含まれてないです

んや、それはそうなんですけど、既存の判定([deep-email-validator](https://www.npmjs.com/package/deep-email-validator))にwhiltelist対象が入ってたりみたいなことはないかな…?という意図です

**Comment by anatawa12** [comment]
それを許可する実装を組み込むつもりはなかったけどやる前提でいた？

**Comment by Sayamame-beans** [comment]
> それを許可する実装を組み込むつもりはなかったけどやる前提でいた？

最初は無かったので
> blacklistだけじゃなくてwhitelistあるっぽいんだけどどうなんだろうね(blacklist内容追加だけで良いのかな)

という言葉に繋がります。
whitelistあるんだったらそれも意識した方が良いのかな…? という疑問が生まれたということです。

**Comment by Sayamame-beans** [comment]
ん…? そもそもdeep-email-validatorのdisposable判定ってdisposable-email-domainsなんですね(気付いてなかった)

**Comment by anatawa12** [comment]
~~そうではあるが `disposable-email-domains` が更新されてない (npmにおいて)~~

**Comment by anatawa12** [comment]
そもそも"disposable-email-domains"の指してる先が全く別

npmのdisposable-email-domainsはこれ https://github.com/ivolo/disposable-email-domains?tab=readme-ov-file

**Comment by Sayamame-beans** [comment]
🤯 
別物か…

**Comment by anatawa12** [comment]
bannedEmailDomainsに追加する方針になったので(内部discord参照)misskey側ではやらないのでclose
