### ISSUE TITLE
更新時に各自の環境で壊れることがあることの対策する

### ISSUE THREAD

**Issue by anatawa12** [niwaniwa/misskey#155]

**Comment by anatawa12** [comment]
https://misskey.niri.la/notes/9pz86b1skg
https://misskey.niri.la/notes/9pz7fp8oa8
https://misskey.niri.la/notes/9pz7f0ng4l

**Comment by KisaragiEffective** [comment]
related?: #152

**Comment by anatawa12** [comment]
404に対するCache-Controlはmisskey出だしてるわけではなさそう。

<img width="1445" alt="Screenshot 2024-02-22 at 15 36 54" src="https://github.com/niri-la/misskey.niri.la/assets/22656849/3ea4c04e-67b9-436b-ad98-f93f2a6c325b">

**Comment by niwaniwa** [comment]
<img width="806" alt="image" src="https://github.com/niri-la/misskey.niri.la/assets/10182706/206c68fb-b038-4bbd-88d0-cc7a803ffad5">
Cloudflare側にcache設定を発見👀

**Comment by anatawa12** [comment]
↑で治ったっぽい
