### ISSUE TITLE
ミスキーを利用時にビープ音が再生される

### ISSUE THREAD

**Issue by RearAlice** [niwaniwa/misskey#156]
### 💡 概要

利用時にビープ音が3回再生される。
システムから流れているものではなく、ページからの再生マークが出ているので、表示されていない音設定の何かしらの設定なのかもしれない。

### 🥰 想定される挙動

ならないのが望ましい

### 🤬 Actual Behavior

Uncaught (in promise) Error: locale fetching error
    at W._fetch (sw.js:1:16155)

### 📝 再現手順

にりらみすきーを表示し、放置。

### 💻 お使いの環境

```markdown
* 機種とOS:Mac Windows問わず
* ブラウザ:Safari（最新版） MSedge（最新版）Chrome （最新版）Brave（最新版）
```

**Comment by Sayamame-beans** [comment]
追加情報
- 10分～30分程度の放置で鳴る(3回鳴るので1セット)
その後また時間を空けて鳴る模様
- タブを表示したまま放置、バックグラウンドで放置のどちらでも発生する
- misskey.ioでは発生しない
- Safari サポート曰く、サイト側で鳴っている

**Comment by RearAlice** [comment]
追加情報
- おそらくオリジナルに近いななみさんのところのサーバーではならない。（グローバル、ホーム問わず）
- にりみす部内だとどのページでもなる模様（通知ページとかでもなるときは鳴る）

**Comment by anatawa12** [comment]
> Uncaught (in promise) Error: locale fetching error
at W._fetch (sw.js:1:16155)

とありますが、スタックトレースはこれ以上ない感じですか

**Comment by Sayamame-beans** [comment]
再現出来ないかも。
以下を今一度ご確認下さい。
- 発生条件は時間経過のみである? (放置は条件ではなく、"放置でも起こる"だけ?)
- デフォルト. クラシック, デッキのいずれのUIを使用していますか?
- 通知を発生させないタイプの通知音ではない? (チャンネル通知)
- 音はsyuiro/tripleとは異なる? (通知音の中で、3連で音が鳴るもの)
- Actual Behaviorとして挙げられているエラーは、音が鳴る度に出ている?

**Comment by RearAlice** [comment]
- 発生条件は時間経過のみである? (放置は条件ではなく、"放置でも起こる"だけ?)
  　今の所、放置以外にも、通知ページにいてもなっている。ページ作業中でもなることもある。

- デフォルト. クラシック, デッキのいずれのUIを使用していますか?
　　デフォルトです。 
- 通知を発生させないタイプの通知音ではない? (チャンネル通知)
  　ではないと思います。
- 音はsyuiro/tripleとは異なる? (通知音の中で、3連で音が鳴るもの)
  確認しましたが違いました。今度なった時でもここに貼り付けます。
- Actual Behaviorとして挙げられているエラーは、音が鳴る度に出ている?
  ではなさそう。常にエラー吐いてます。
![https://media.niri.la/misskey/d0242469-7c31-43dc-94c5-5fca1893e637.png](https://media.niri.la/misskey/d0242469-7c31-43dc-94c5-5fca1893e637.png)
> [!NOTE]
> エラーログは、なったタイミングのログのため、ブラウザによってエラー内容違うかもしれません。他のブラウザでも確認中です。
  **よく使っているのがMS edgeとSafariのため**


### 通常時ログ

[log_safari.log](https://github.com/niri-la/misskey.niri.la/files/14369223/log_safari.log)
[misskey.niri.la-1708579966724_chrome.log](https://github.com/niri-la/misskey.niri.la/files/14369231/misskey.niri.la-1708579966724_chrome.log)
[misskey.niri.la-1708579931846_edge.log](https://github.com/niri-la/misskey.niri.la/files/14369235/misskey.niri.la-1708579931846_edge.log)

### なった時のログ

[misskey.niri.la-1708581506431_edge.log](https://github.com/niri-la/misskey.niri.la/files/14369660/misskey.niri.la-1708581506431_edge.log)

> [!WARNING]
> コンソールログになるため、個人情報はおそらく含まないと思われますが、取り扱いにご注意ください。

**Comment by newdays-git** [comment]
[log_safari.log](https://github.com/niri-la/misskey.niri.la/files/14369223/log_safari.log)

**Comment by anatawa12** [comment]
misskey-dev#13379 関係あったりするかな。
2024.2.0-io.2dに[含まれてる](https://github.com/MisskeyIO/misskey/commit/f18a31c628aa2ce21599a3706bda06953bfe6e09) しななみさんのところもdevelopなので

**Comment by Sayamame-beans** [comment]
Audio context was not allowed to startは確かに爆音問題のログではある…(操作していない状態だと音が鳴らない挙動をするもの)

**Comment by anatawa12** [comment]
ぶいそ(2024.2.0 + patches = うちにちかい)で発生するかとかかなぁ

**Comment by RearAlice** [comment]
16:35頃に鳴ったのでhttp(s)HARログデータ
[misskey.niri.la_http_log_edge.zip](https://github.com/niri-la/misskey.niri.la/files/14370500/misskey.niri.la_http_log_edge.zip)

**Comment by RearAlice** [comment]
現段階でなった時にあるのが
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`っていう警告文ですね。

**Comment by RearAlice** [comment]
現段階の傾向調査した感じだとミスキーがノンアクティブ（別タブで別ページを開いて隠れてる）の時になることが多いかもしれません。ここで出てるぶいちゃ.socialに一度登録して同症状でるか確認してみます。

**Comment by RearAlice** [comment]
結局、使っていてもなってるのでわからなくなってきた感じです。
ちなみにそのなった時にログ見たら真っ白で`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`すらなかったです。
あとぶいそだと現時点では再現しない（謎）

**Comment by Sayamame-beans** [comment]
triage: 現象が再現されないままですし、他の方からの報告も無いので閉じます。
まだ起こっているか、他の人の環境で発生した場合はご報告ください。
