### ISSUE TITLE
ノート検索が正常に機能していない

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#168]
### 💡 概要

検索対象の文字列を入力して検索すると、その文字列が含まれているはずのノートが十分に表示されない(一部のみ表示される)。

Misskey標準の検索は前方一致で、現在のにりみすではMeilisearchを導入して検索の機能を拡張していますが、標準より検索精度が劣ってはならないと考えます。

### 🥰 想定される挙動

検索対象に該当するノートが全て表示される。

### 🤬 実際の挙動

一部しか表示されない

### 📝 再現手順

多分簡単に確認出来る例
1. 単語を設定したアンテナを建てる
2. アンテナにノートが溜まるのを待つ
3. その単語を検索してみる

### 💻 お使いの環境

```markdown
* 機種とOS: any
* ブラウザ: any
```

**Comment by anatawa12** [comment]
例を適当に集積します
AAOで引っかからない: https://misskey.niri.la/notes/9rbzpbi8i4

他にも例があればください

TODO: 
- [ ] meilisearch側にissue
- [ ] meilisearchの裏のtokenizerの方の確認
- [ ] ローカルのmeilisearchでの動作確認

**Comment by niwaniwa** [comment]
meilisearch-ui側で確認したところ、misskeyと同様の検索結果が出ているので、Meilisearch側のデータに問題があるかもしれない

![image](https://github.com/niri-la/misskey.niri.la/assets/10182706/209fd96e-0e0a-4248-bace-61cdd4d7c2d5)

「検索」でひっかからない: https://misskey.niri.la/notes/9rc1t7npy3

**Comment by Sayamame-beans** [comment]
さやまめチェッカー(にりみすのMisskey Play)の共有ノートに含まれる`さやまめです。`で検索した場合、3月の分は https://misskey.niri.la/notes/9qbsa0eenx しか出ません。
実際にはかなり沢山あります。([`#さやまめチェッカー`](https://misskey.niri.la/tags/%E3%81%95%E3%82%84%E3%81%BE%E3%82%81%E3%83%81%E3%82%A7%E3%83%83%E3%82%AB%E3%83%BC)を参照)
(なんなら`さやまめチェッカー`も今月分は https://misskey.niri.la/notes/9qb135shly と https://misskey.niri.la/notes/9qb0uz3qql しか出ない)

**Comment by niwaniwa** [comment]
使用したツール
https://github.com/noellabo/misskey_meilisearch_importer

**Comment by niwaniwa** [comment]
関連issue: https://github.com/orgs/meilisearch/discussions/532

> A Query containing Kanjis doesn't retrieve all the relevant documents
> When doing a search query with only characters, the language detection doesn't classify the query as a Japanese one but as a Chinese one because:Kanji

2022ですが言語自動判定によって漢字のものは中国語系と判定されるみたい？
無効化するImageがあるのでそれを使っても良さそう(とはいえさやまめさんが出てこないのは謎

**Comment by Sayamame-beans** [comment]
"canny"とかURLとかでも漏れてるっぽいので、日本語に限った問題では無い気が少しします

**Comment by Sayamame-beans** [comment]
この問題、複合要因っぽいか…
- 言語判定の問題で出ない場合
- 形態素解析の問題で出ない場合
- 純粋にMeiliSearch Web UIとMisskeyで検索結果が違う場合

**Comment by niwaniwa** [comment]
使用されている形態素解析がlinderaとのことだったのでさやまめさんの単語を解析した結果以下のように。

<img width="92" alt="image" src="https://github.com/niri-la/misskey.niri.la/assets/10182706/1d1b03a2-5afe-4574-b77a-b9cfacd4def8">

とりあえず言語判定を日本語にするImageに変更しました。
どうやらMeilisearchにもユーザー辞書があるので、どこかで一気にユーザー辞書を登録してあげてもいいかもしれない。

これとは別にmeilisearch側で確認したのですが、createdAtの条件を付与したところ、なぜか指定していない時に表示されていたノートが表示されなくなってしまいました。

検索: `さやまめ`
フィルタ条件: `createdAt < 1708774740872 AND userHost IS NULL`
ソート: `createdAt: desc`

**Comment by Sayamame-beans** [comment]
とりあえずMeilisearchを無効化したので閉じ
