### ISSUE TITLE
ノートのエクスポートが完了しない

### ISSUE THREAD

**Issue by KisaragiEffective** [niwaniwa/misskey#169]
### 💡 概要

ノートのエクスポートが完了しない

### 🥰 想定される挙動

ノートのエクスポートが30分ぐらいで完了する

### 🤬 実際の挙動

いつまで経っても完了しない: https://misskey.niri.la/notes/9rlclw1rhg

### 📝 再現手順

1. いっぱいノートする
2. ノートのエクスポートを要求する

### 💻 お使いの環境

```markdown
* 機種とOS: Debian 12 (Linux kernel 6.5.0-0.deb12.4-amd64)
* ブラウザ: Firefox 123.0


$ uname -a
Linux debian12-gen13 6.5.0-0.deb12.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1~bpo12+1 (2023-11-23) x86_64 GNU/Linux
$ firefox --version
Mozilla Firefox 123.0
```
```

**Comment by Sayamame-beans** [comment]
こちら、現在も発生していますか?

**Comment by KisaragiEffective** [comment]
再検証するためにエクスポートをリクエストしました: https://misskey.niri.la/notes/9rvdlgmz7h

**Comment by KisaragiEffective** [comment]
再度検証しましたが、やはりドライブに上がってきません。

**Comment by Sayamame-beans** [comment]
私も試してみましたが、比較的すぐに(5分以内ぐらい?)終わったので、何らかの例外を吐いている可能性がありそうです
タイミングを計ってこちらでログを観測するのが良いかもしれません

**Comment by KisaragiEffective** [comment]
revisit: さっき試したらちゃんとエクスポートされてました。機嫌が悪かったのかも

**Comment by Sayamame-beans** [comment]
謎
一旦完了としますね(再発したら開いてください)

**Comment by KisaragiEffective** [comment]
meilisearchがなくなってから(？)3分程度で完了するようになったので、meilisearchや設定変更によって解決されてそうです
