### ISSUE TITLE
可逆圧縮のみ行うオプションの追加

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#17]
## Summary

https://misskey.niri.la/notes/9hlwb11gee
> webp可逆のリサイズ無しオプションがあれば嬉しさが…? 
> ふむ、つまり可逆圧縮するか、可逆が無理なものはオリジナルで投稿するかっていう風になるオプションがあると個人的にはとっても嬉しいわけだ…?

圧縮が有効な場合、現在はリサイズ後に圧縮が行われます。
リサイズを行わず、webpへの可逆圧縮が可能な場合においてのみ変換/圧縮を行い、そうでない場合はオリジナルのままにするオプションが欲しいです。

**Comment by anatawa12** [comment]
これってjpgとかも可逆にする想定...? resizeなしでwebp非可逆かけてもよし?

**Comment by Sayamame-beans** [comment]
元が非可逆なやつは悩ましいですね…(考慮するの忘れてました)
既に非可逆圧縮による劣化はしている訳なので…
でも、このissueの方向性から考えるなら、可逆にするか何もしない(圧縮なし)ですかね…?

**Comment by Sayamame-beans** [comment]
このオプションを言い換えるならば、「自分が意図した状態から変化させたくないが、出来るなら軽くしたい」オプションと言えます。勿論、それなら自分で圧縮しろというのは大いにあると思いますが…

**Comment by anatawa12** [comment]
resizeなしでwebp非可逆実装にしました。理由としては

- 再圧縮なしは手動で選べば良いのでoptionとしてはなくていいかな
- 可逆圧縮すると元ファイルより大きくなるので意味がない

の２点からこのように選択しました。

現状元がwebpだとlossyだと判断してるのでlosslessかどうかを判断するコードは可能化を検討中

**Comment by Sayamame-beans** [comment]
良いと思います
