### ISSUE TITLE
ぶいみみリレータイムラインにおいて、DBフォールバックの内容が正しくない可能性がある

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#178]
### 💡 概要

時間か数のどちらがキーか分かりませんが、リノートを表示 + TLに他の人への返信を含める を有効にした状態で1時間程度前まで遡ると、リプライしか表示されなくなりました。
直近1時間の内容は正常(リプライ以外の内容も含まれる)です。

追記: ぶいみみリレータイムラインと同様の内容が流れるぶいみみソーシャルタイムラインでも同様でした。

### 🥰 想定される挙動

全ての投稿が含まれる

### 🤬 実際の挙動

一定より前の内容はリプライのみ含まれる

### 📝 再現手順

時間経過?

### 💻 お使いの環境

```markdown
* 機種とOS: any
* ブラウザ: any
```

**Comment by Sayamame-beans** [comment]
TLに他の人への返信を含める を無効にした状態であれば、含まれているように見えます。
withRepliesがあるときのqueryがおかしい?

**Comment by Sayamame-beans** [comment]
https://github.com/niri-la/misskey.niri.la/blob/81dad3f00e8acc8138a4d63bfee01d6103dd116d/packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts#L171-L181

https://github.com/niri-la/misskey.niri.la/blob/81dad3f00e8acc8138a4d63bfee01d6103dd116d/packages/backend/src/server/api/endpoints/notes/local-timeline.ts#L170-L180

ここだけ見ると差が無いように見えるので、前後との組み合わせの問題ですかね～
LTLではwithFilesが前に来ていて、VRTLでは後ろに(withFiles含め)色々来ている形なので、前方になったwithRepliesで絞りすぎている?

**Comment by Sayamame-beans** [comment]
ん…? それだとVSTLも駄目なことの説明が付かない?
https://github.com/niri-la/misskey.niri.la/blob/81dad3f00e8acc8138a4d63bfee01d6103dd116d/packages/backend/src/server/api/endpoints/notes/vmimi-relay-hybrid-timeline.ts#L224-L234

**Comment by anatawa12** [comment]
他人を含めるがオフだとどうなりますか

**Comment by Sayamame-beans** [comment]
> 他人を含めるがオフだとどうなりますか

↓
> TLに他の人への返信を含める を無効にした状態であれば、含まれているように見えます。 withRepliesがあるときのqueryがおかしい?

**Comment by Sayamame-beans** [comment]
ユーザーページで一定期間より前まで遡ったケースで、"全て"ではリプライかチャンネル投稿しか見えなくなるが、"ノート"では問題なく見える挙動があるようです。
もしかしてこれ、DB FallbackのwithReplies系のqueryが(本家含め)全体的に間違っていたりしますか?
ref: https://misskey.niri.la/notes/9sbbf8n2w0

**Comment by anatawa12** [comment]
そもそもdb fallback起因であるか確認したいかも

FTTのマージのバグとしてFTTキャッシュの長さがだいたい同じであるという仮定してて、長さが違うと短いやつが終わると長いやつのだけ見れるようになるのはあるので、VRTLについては見れなくなるのが300ノート以上継続するか確認したい

**Comment by Sayamame-beans** [comment]
あー

**Comment by anatawa12** [comment]
要するに: misskey-dev#13488 の可能性

**Comment by Sayamame-beans** [comment]
VRTL、300ノート継続しないですね
280ぐらい遡ったら直りました(APIの応答の数が明らかに欠けますね)
こっちは13488か…

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/issues/13488 っぽいので close as not planned します

misskey-dev/misskey#13495 取り込んでもいいかもね

**Comment by Sayamame-beans** [comment]
13495、なんか直さないとって言ってた記憶が朧げにあるので取り込むべきじゃないかも

**Comment by anatawa12** [comment]
コメントにあるけどFTTが空だと常にfallbackされるってのある。けどこれは仕方ない仕様だと思うので

**Comment by Sayamame-beans** [comment]
確かに。じゃあうちで試験導入しても良いかもですね〜
