### ISSUE TITLE
ノートのホーム化をしてもVRTLからノートが非表示になっていない

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#186]
### 💡 概要

PublicノートをHome化した際、LTLからは消えるようですが、その他のTLからは消えていないかもしれません。
(VRTLでは消えていないことを確認しました。GTLは密度的に消す処理なくても大丈夫そうですが既に消えてそう?でした。)
https://github.com/niri-la/misskey.niri.la/blob/38526a8d48cb0a980a813f303895789818af62d7/packages/backend/src/server/api/endpoints/admin/note-public-to-home.ts#L118-L132

### 🥰 想定される挙動

VRTLから消える

### 🤬 実際の挙動

VRTLに残る

### 📝 再現手順

1. ぶいみみリレー内のリモートのノートをHome化する
2. VRTLをリロードする
3. 見える

### 💻 お使いの環境

```markdown
* 機種とOS: any
* ブラウザ: any
```

**Comment by Sayamame-beans** [comment]
これって`vmimiRelayTimeline`とかに同じことすれば良いんですかね～…?

**Comment by Sayamame-beans** [comment]
直ってないかも。
https://misskey.niri.la/notes/9tckfu8ur3

**Comment by Sayamame-beans** [comment]
ローカルの投稿に対して適用したときが駄目かも。
リモートの投稿に対しては大丈夫かも。

**Comment by Sayamame-beans** [comment]
両方処理入ってるように見えるのになんでだろう

**Comment by anatawa12** [comment]
https://github.com/niri-la/misskey.niri.la/pull/189#issuecomment-2102601907 完全に忘れてマージしたけどこれな気がする

**Comment by Sayamame-beans** [comment]
なるほどね()

**Comment by Sayamame-beans** [comment]
質問なんですが、LTL/VRTLやSTL/VSTLのLTL成分から、リアルタイムに当該ノートの削除走らせるって可能なんでしょうか?
STLは厳しい? (HTL成分と重複するから一緒に消えてしまう?)

**Comment by anatawa12** [comment]
一応がんばりゃできる

**Comment by Sayamame-beans** [comment]
> > 質問なんですが、LTL/VRTLやSTL/VSTLのLTL成分から、リアルタイムに当該ノートの削除走らせるって可能なんでしょうか?
> > STLは厳しい? (HTL成分と重複するから一緒に消えてしまう?)

> 一応がんばりゃできる

検討します
