### ISSUE TITLE
バージョン名がsemver的にあまりよろしくない

### ISSUE THREAD

**Issue by anatawa12** [niwaniwa/misskey#2]
`13.13.2-kinel-0.0.1`だと`13` `13` `2` `kinel-0` `0` `1`と分割されてしまう。`13.13.2-kinel.0.0.1`の形式に変更する
次の更新から

**Comment by Sayamame-beans** [comment]
solved?

**Comment by anatawa12** [comment]
yes

13.14.2-kinel.1で解決
