### ISSUE TITLE
ウィジェット内のタイムラインでVRTL / VSTLが選択できない

### ISSUE THREAD

**Issue by shirasu256** [niwaniwa/misskey#200]
デッキUIのカラムとしてのタイムラインではなく、デフォルト / デッキ / クラシックUIのウィジェットに追加できるタイムラインウィジェット内で、VRTL / VSTLが選択できません。
![mosaic_20240615131338](https://github.com/niri-la/misskey.niri.la/assets/168863443/3b3f4555-bf65-44ef-b0db-c88f59e4fe40)

昨晩anatawaさんと口頭で話したのをissue化

**Comment by Sayamame-beans** [comment]
(VRTL側に建てるissueかも…?)

**Comment by anatawa12** [comment]
owner違うとtransferできないのか... anatawa12/misskeyに立て直します

**Comment by anatawa12** [comment]
Manual Transfer to  anatawa12/misskey#32
