### ISSUE TITLE
名前を空白文字列だけにできるように戻す

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#218]
### 概要

https://github.com/misskey-dev/misskey/pull/14119 (表示名の設定が空欄の場合、アカウント名(私の場合`Sayabeans`)が表示されるようになる)をrevertする

### 目的

名前への空白文字の入力を防ぐ理由が特に無い
また、防いだとしてもその他の空白文字や`:blank:`があるので効果が無い
https://github.com/misskey-dev/misskey/issues/14088#issuecomment-2204924852 (←この問題はこの問題の側を解決するべき)

**Comment by Sayamame-beans** [comment]
@anatawa12 今回のリリース(2024.7.0-kinel.1?)に含めます

**Comment by anatawa12** [comment]
うーん:blank:で効果がないはそうなんだけど、わざわざ許可する意味を見いだせない

**Comment by Sayamame-beans** [comment]
> うーん:blank:で効果がないはそうなんだけど、わざわざ許可する意味を見いだせない

にりみすは既にこれに該当するユーザーが居るので、逆に、わざわざ禁止する意味を見いだせなければ弾きたい(入れたくない)という気持ちです

**Comment by anatawa12** [comment]
私からしたらupstreamから変える意味がないなら変えたくない気持ちがある

**Comment by anatawa12** [comment]
@niwaniwa りらさんに判断してもらおう

**Comment by niwaniwa** [comment]
さやまめさんのおっしゃる通り、特段禁止する必要は感じないのかなと思います(現状使用しているユーザーも存在するため。)
私の意見としてはユーザー表現の手段を抑制するような変更は、セキュリティ的なデメリットが存在しない場合upstreamに追従しなくても良いと思います。
(Upstreamからわざわざ変更するのもな、、、というのもわかる)

**Comment by anatawa12** [comment]
となるとトリム自体も消す感じですかね

**Comment by Sayamame-beans** [comment]
うーん
空白だけの長い名前によって、アカウント名やサーバーURLを隠せてしまうというのがありますが、これは空白でなくても発生する問題ではあり…
特段空白だけを規制する必要はない(トリムもrevertする)か?という気持ちと、空文字列("")で表示名を空に出来たら十分か?という気持ちと…(にりみすに居る方は多分アカウント名を隠すような長さにはしていなかった気がするので)

**Comment by anatawa12** [comment]
PRまとまってるので両方revertがらくではある

**Comment by Sayamame-beans** [comment]
じゃあ両方revertで良いかな〜
空白文字列固有で、かつ、この部分で対応することが適切な問題で困った時に導入を考えようかなと思います
