### ISSUE TITLE
ホーム投稿化によるTL削除がVRTLのリプライ部分に適用されていないっぽい

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#227]
### 💡 概要

タイトル通り

### 🥰 想定される挙動

ホーム投稿化によって(リロードで)見えなくなる

### 🤬 実際の挙動

リプライに対しては残っている

### 📝 再現手順

1. パブリック投稿にリプライする
2. それをホーム投稿化する
3. リロードする

### 💻 お使いの環境

```markdown
* 機種とOS: any
* ブラウザ: any
```

**Comment by anatawa12** [comment]
よく見たら #191 で削除する対象間違ってるやん
