### ISSUE TITLE
ミュートしている人の投稿等が見える?

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#23]
https://misskey.niri.la/notes/9hueslsbe2

**Comment by anatawa12** [comment]
upstreamになげよ...?

**Comment by Sayamame-beans** [comment]
情報少ないので厳しい

**Comment by KisaragiEffective** [comment]
閲覧したユーザーVが以下のようなツリーでb1を見た時、VがユーザーAをmuteしているのにa1が見えてしまう(Twitterではa1が折りたたまれて表示されるので、UXの観点からは直感的ではない)という話ではないでしょうか？
- a1 (by A)
  - b1 (by B)

**Comment by Sayamame-beans** [comment]
なるほど、b1の詳細ページを開いた際にa1がそのまま見えるのが困るということですね。

**Comment by KisaragiEffective** [comment]
はい

**Comment by Sayamame-beans** [comment]
初めに言及したノートでの`そこから詳細に飛んでも`の前の部分は謎という感じもあります…
(ノートにある通り、チャンネルTLの都合なのかもしれませんが)

とりあえず、詳細ページを開いた際にミュート対象を畳んで欲しいという点については本家issueに投げられそうです
