### ISSUE TITLE
フォローリクエストを承認したあとページ更新するとまた承認ボタンが出る

### ISSUE THREAD

**Issue by RearAlice** [niwaniwa/misskey#232]
### 💡 概要

フォローリクエストを承認したあとページ更新するとまた承認ボタンが出る

### 🥰 想定される挙動

フォローリクエストを承認してボタンは消えるはずです。

### 🤬 実際の挙動

ボタンが出続ける

### 📝 再現手順

https://github.com/user-attachments/assets/02fbe16e-4fd3-402a-a178-3fd56ff0c6ac

見れない場合
https://misskey.niri.la/notes/a0h6la3p8l

### 💻 お使いの環境

```markdown
* 機種とOS:Windows、Mac問わず
* ブラウザ:Safari、brave、MSedge
```

**Comment by Sayamame-beans** [comment]
upstream issue: https://github.com/misskey-dev/misskey/issues/13378
thank you for reporting!
