### ISSUE TITLE
sensitiveチャンネルの投稿をnoindexにするか選択可能にする

### ISSUE THREAD

**Issue by anatawa12** [niwaniwa/misskey#37]
## Summary

#34 の残りtask

**Comment by anatawa12** [comment]
これそもそもindexしたいって理由あるのかな...

**Comment by Sayamame-beans** [comment]
微妙…
サーバーによっては通常のTLに流さずにチャンネルに色々投稿する可能性が挙げられるけど、にりらみすきー部だと(少なくとも現状では)不要そうな気もする…?

**Comment by anatawa12** [comment]
しかもセンシティブのみなので需要がわからん

**Comment by anatawa12** [comment]
とりあえずnot plammedとしてcloseして要望があるかどうかって感じかな
