### ISSUE TITLE
センシティブチャンネルの投稿をユーザーページで表示するための設定項目が見当たりません

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#38]
設定項目が見当たりません
> > 設定/全般/ノートの表示 辺りですかね。ノートの表示の上(タイムラインに返信表示する項目の所)でも良いかもしれません
> 
> 良さそう　thx

_Originally posted by @Sayamame-beans in https://github.com/niri-la/misskey.niri.la/issues/10#issuecomment-1667076436_

**Comment by Sayamame-beans** [comment]
@anatawa12 これも`13.14.2-kinel.3`までに解決が必要です。

**Comment by anatawa12** [comment]
これcollapseにしたからいらないかなと思ったんだけどいる？
