### ISSUE TITLE
センシティブチャンネルへの投稿の折り畳み表示をもっといい感じにしたい

### ISSUE THREAD

**Issue by meronmks** [niwaniwa/misskey#39]
## Summary
現状長文投稿がされた時と同じ畳まれ方となっているが、本文としては見えてない方が適切と思われる為
何かしらの本文置き換え（ソフトミュート的な表示）がされているとうれしいかも

<img width="597" alt="image" src="https://github.com/niri-la/misskey.niri.la/assets/12034371/1294f0a3-a9f3-4d18-979d-5700ad5271fb">

**Comment by anatawa12** [comment]
とりあえずやった感じなので修正のつもりはあります。issue起票感謝です
