### ISSUE TITLE
Misskey付属のwebhookをDiscordに対応させる

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#4]
## Summary

Misskeyでは、アカウントの一部操作に対してwebhookが設定可能。(ちょっと古いかもですが、参考: https://misskey-hub.net/docs/features/webhook.html )
ですが、これはDiscordの形式には対応していないようです。
これを対応させられると、Misskey通常利用時に私たち(管理者)が確認出来ない、公式アカウントへのリプライやメンションをDiscordに流し、気付くことが出来るので便利になりそうです。

あと、一般ユーザーさんでも便利に使ってくれる人が居るかも。

**Comment by Sayamame-beans** [comment]
ただし、管理アカウントでの利用という点においては、こちらのissue( https://github.com/misskey-dev/misskey/issues/10975 )で言及されている問題が影響する可能性がある。
その意味では、webhookを利用するよりMisskey APIを利用するbotとして用意した方が(管理アカウント周りで利用するには)良い可能性がある。

**Comment by anatawa12** [comment]
@Sayamame-beans @niwaniwa misskeyのwehookに種別の概念がないので実装の都合で中継サーバでの処理にしたいです。

secretを特定の単語にするとかやり方なくはないですが、様々なwebhookイベント種別があるのでそれぞれに対するmisskey内部でメッセージの構築をあまりやりたくないです。

**Comment by Sayamame-beans** [comment]
私はOKです (わざわざ中継しなきゃ駄目なんだ〜…と思ってたんですが、それが最適ならその方が良さそうですね)

**Comment by anatawa12** [comment]
https://github.com/niri-la/misskey-discord-webhook-proxy
