### ISSUE TITLE
ユーザーページ内のセンシティブチャンネルのノート以外、全てのノートが畳まれなくなっている

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#41]
## 💡 Summary

センシティブチャンネルでないノートの畳み判定が機能していないようです。
原因調査中。

## 🥰 Expected Behavior

長かったり拡大MFMを使っていたりすると畳まれる。

## 🤬 Actual Behavior

センシティブチャンネル以外畳まれない。

## 📝 Steps to Reproduce

1. `$[x2 test]`などを投稿する。
2. タイムラインを眺める。

### 💻 Frontend
* Model and OS of the device(s): Windows 10 Pro 22H2
  
* Browser: Google Chrome 115.0.5790.171
  
* Server URL: https://misskey.niri.la
  
* Misskey: 13.14.2-kinel.2

**Comment by Sayamame-beans** [comment]
ユーザーページ内のセンシティブチャンネルのノートは畳まれていますが、タイムライン上(RNで試しました)ではセンシティブチャンネルのノートでも畳まれていないようです…?

**Comment by Sayamame-beans** [comment]
should be related: #35

**Comment by anatawa12** [comment]
演算子の優先旬位でやらかしたかも

**Comment by Sayamame-beans** [comment]
~~当初、`shouldCollapsed()`が怪しいかと思いましたが、ここには問題がないように思います。~~
~~というのも、`$[x2`などは短絡評価で先に抜けられるはずにも関わらず、畳まれていないからです。~~
完全にここでした
