### ISSUE TITLE
"Misskeyについて"の項目に、にりらみすきー部の情報を加える?

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#43]
## Summary

リポジトリへのリンクなど、あっても良いのかなと…
related: https://github.com/niri-la/misskey.niri.la/blob/develop/packages/frontend/src/pages/about-misskey.vue

**Comment by anatawa12** [comment]
gh link追加は良さそ

**Comment by Sayamame-beans** [comment]
よく考えたらローカライズが絡むんですね…これ

**Comment by anatawa12** [comment]
別にjaハードコードでもどっちでもいいと思うよ
