### ISSUE TITLE
ダイレクトのRNを消去すると500が返ってくる

### ISSUE THREAD

**Issue by KisaragiEffective** [niwaniwa/misskey#56]
## 💡 Summary

投稿範囲をダイレクトにしたノートをRNし、そのRNを取り消すとステータスコードが500のレスポンスとエラーが返ってくる

(※おそらく misskey-dev/misskey#10127 と同根のバグだと思われるが、upstreamで発生するか検証していないため一旦このリポジトリに記録)

## 🥰 Expected Behavior

200などで正常に消去される

## 🤬 Actual Behavior

消去はされているように見えるが、レスポンスでエラーが返ってくる

## 📝 Steps to Reproduce

1. 投稿範囲をダイレクトにしたノートをする
2. ノートをリノートする
3. リノートを取り消す

<details>

<summary>再現用自動スクリプト</summary>

```bash
#!/bin/bash
MISSKEY_TOKEN="put your token"

if ! command -v jq &> /dev/null
then
    echo "This script requires jq"
    exit
fi

jq -n --arg TOKEN "$MISSKEY_TOKEN" '{"text":"1","poll":null,"localOnly":false,"visibility":"specified","visibleUserIds":[],"reactionAcceptance":null,"i": $TOKEN }' | \
  curl 'https://misskey.niri.la/api/notes/create' -X POST -H 'Content-Type: application/json' -d@- | \
  jq --arg TOKEN "$MISSKEY_TOKEN" '{ "localOnly": false, "renoteId": .createdNote.id, "visibility": "specified", "i": $TOKEN }' | \
  curl 'https://misskey.niri.la/api/notes/create' -X POST -H 'Content-Type: application/json' -d@- | \
  jq --arg TOKEN "$MISSKEY_TOKEN" '{ "noteId": .createdNote.id, "i": $TOKEN }' | \
  curl 'https://misskey.niri.la/api/notes/delete' -X POST -H 'Content-Type: application/json' -d@-
```

</details>

### 💻 Frontend

`13.14.2-kinel.4`

### 🛰 Backend (for server admin)

`13.14.2-kinel.4`

**Comment by anatawa12** [comment]
同根ではありそうですがそもそもdirect投稿がrenoteできる方にissueが向きそうな気もするのでupstreamに投げます。

**Comment by anatawa12** [comment]
UpstreamでRNできることの方をいじったのでCloseします
