### ISSUE TITLE
リレータイムラインの導入について

### ISSUE THREAD

**Issue by niwaniwa** [niwaniwa/misskey#57]
## Summary
リレーを行っているサーバーのみのタイムラインの導入

## Why
現状リレーのノートは連合に流れるが、他の連合ノートで埋もれてしまい、現状リレーの利点が失われている為

**Comment by niwaniwa** [comment]
出来るかはさておき検討はしたいかも(私が欲しいだけ)

**Comment by anatawa12** [comment]
リレーから来たnoteかの判断の方法がぱっと見なさそうなのでやるとしたらサーバーを手動指定しないといけない気がします

**Comment by anatawa12** [comment]
https://misskey.niri.la/notes/9q96otdr80

https://relay.virtualkemomimi.net/api/servers があるようなのでこれで実装を検討していい気がする

**Comment by Sayamame-beans** [comment]
最低限の実装で考える場合に…
コントロールパネルにあるリレーサーバーの設定欄に表示名の設定は必要かも。
/api/以下のどこか(metaとか?)にめうるみさんが埋め込んでくれると解決はします。

**Comment by Sayamame-beans** [comment]
リレーサーバーのアイコン表示は正直必要ないと思っています(表示する場所がない…)
とはいえ、「リレータイムライン」用のアイコンは必要そうです(STLとかHTLとかのアイコンみたいに)

**Comment by anatawa12** [comment]
少なくとも当面はVけも専用リレーtlになるので、全部ハードコードのつもり

**Comment by Sayamame-beans** [comment]
考えていること

GTLがLTLより短いなら、そしてそれが極端に差があるなら、保存期間はその間ぐらいが無難そう。
(少なくとも今は流速が異なるので)

DB fallbackについては、以前の分は考えていなくて、実装後にDBに突っ込まれた分で良いかなと思ったりしている。
新設される訳なので、それ以前が無いのは仕方ないかなという気持ちがある。

GTLは連合なし指定のローカルノートも流れるようですが、RelayTL(RTL?)でも連合なし指定を流れるようにするかどうか…?

**Comment by anatawa12** [comment]
> GTLは連合なし指定のローカルノートも流れるようですが、RelayTL(RTL?)でも連合なし指定を流れるようにするかどうか…?

サーバー制限付きGTLとして実装しようとしてたので何も言わなかったら流れてたけどどうしようか。変えるのは問題なし

**Comment by niwaniwa** [comment]
ローカル指定流れてても良さそうではある
