### ISSUE TITLE
Misskeyサーバー画面について色を変えたい

### ISSUE THREAD

**Issue by niwaniwa** [niwaniwa/misskey#58]
## Summary
https://misskey.niri.la/
非ログイン時の左側に表示される緑色の部分の色を変更したい(例:#FFB3C0)

**Comment by Sayamame-beans** [comment]
表示されている時のhtmlとソースコードを照らし合わせた感じでは、ここかなと思います
https://github.com/niri-la/misskey.niri.la/blob/772d4533e55714aaab6d31703b8b69954ecbcb62/packages/frontend/src/pages/welcome.entrance.a.vue#L99
https://github.com/niri-la/misskey.niri.la/blob/772d4533e55714aaab6d31703b8b69954ecbcb62/packages/frontend/src/pages/welcome.entrance.a.vue#L108
この`--accent`ですが…恐らく、ログイン後にあるテーマ設定で変更可能な値っぽく、そのデフォルト値が現在緑になっているのだと思います。デフォルトでは[Mi Light(内部名`l-light`)](https://github.com/niri-la/misskey.niri.la/blob/772d4533e55714aaab6d31703b8b69954ecbcb62/packages/frontend/src/themes/l-light.json5)な気がするのですが(不明)、そこで指定されていないため、恐らくここが作用しています。
https://github.com/niri-la/misskey.niri.la/blob/772d4533e55714aaab6d31703b8b69954ecbcb62/packages/frontend/src/themes/_light.json5#L12

となると、色々な部分の色に影響が出ることになるので、ちゃんとやるのならば、にりらみすきー部オリジナルのテーマを作ると良さそう?です。
何も考えないことにするならば、先の`var(--accent)`の部分に直接カラーコードを入れたら良さそうな気がします(要検証)。

**Comment by niwaniwa** [comment]
あれはそういうことだったの...!
ならオリジナルテーマ作るのはありですね。色々見てみます！

**Comment by Sayamame-beans** [comment]
Misskeyコントロールパネル上、ブランディング設定の「サーバーデフォルトのライトテーマ」「サーバーデフォルトのダークテーマ」で解決出来そうなのでissue閉じておきますね～
