### ISSUE TITLE
MisskeyをPWAで使用した際に表示されるアイコンをデフォルト画像から変更する

### ISSUE THREAD

**Issue by niwaniwa** [niwaniwa/misskey#62]
## Summary

[Discordの意見＆質問boxでの発言](https://discord.com/channels/1080833190488453140/1097164865988206742/1152146743388012634)がきっかっけ

## 変更例
- `packages/backend/src/server/web/manifest.json`
- `/static-assets/icons/`
どちらかのデータを置換する

**Comment by niwaniwa** [comment]
new verで変わった可能性
要確認

**Comment by anatawa12** [comment]
https://misskey.niri.la/manifest.json
https://misskey.niri.la/static-assets/icons/192.png

変わってないですね。

**Comment by niwaniwa** [comment]
https://github.com/misskey-dev/misskey/commit/814e28459ed70665b63a15f1d6e8152976cd6412
2週間前に追加されたみたいなのでサーバー側で更新Done

**Comment by anatawa12** [comment]
https://media.niri.la/misskey_nirila_192.png になってますね。よさそう
