### ISSUE TITLE
 パブリックで投稿されたノートを後からホーム投稿に変更するモデレーション操作

### ISSUE THREAD

**Issue by anatawa12** [niwaniwa/misskey#78]
> ## Summary
> 
> 利用規約やガイドラインなどにより、パブリックでの投稿は禁止されている内容でも、ホームでの投稿は許可されている場合があります。 或いは、"サイレンス"としてパブリック投稿を制限し、公開範囲の最大をホーム投稿にすることがあります。
> 
> そこで、既にパブリックで投稿されているノートを、後からホーム投稿に変更するモデレーション操作が欲しいと感じました。 連合の面が少し気になりますが、現在でもリモートユーザーに対してサイレンスが機能する(投稿元サーバーでパブリックでも、ローカル側ではホーム投稿として扱うことが可能である)ことから、少なくともローカル側で(変更を連合させずに)ホーム投稿にすること自体には問題が無いと考えています。
> 
> これにより、既に投稿された内容について削除以外の対応が可能になるので、便利です。

https://github.com/misskey-dev/misskey/issues/11435

**Comment by anatawa12** [comment]
実装を調査してみました。

仕様のQuestions
- [x] Home noteがPublic RNされてるって状態になりえそうだけどこれどう処理する? Recursiveに処理するの大変そう => recursiveは本来存在しない。 通常RNはちゃんと対応しよう。
- [x] 同リプライ => 一旦放置
- [x] ほかサーバ(含リレー)に非homeとして配信されてるのはまぁ放置するしかないけどOK? => OK
- [x] Push TLになったあとのTLから消した方がいい？(消さないほうが楽) => 消して
- [x] 各種public only featuredの候補から消した方がいい？(消さないほうが楽) => 消して

実装上の注意点
- PollでnoteVisibilityがDenormalized

要調査
- [ ] APubのペイロードの形(to / cc)変わるけど問題ないんかな (他のサーバが編集機能持ってるから問題ない説ある)

Resolved
- [x] 検索Indexingは - home投稿も含むから問題なし
- [x] pushTLになったあとはlocal TLに残そうだけど消せる？  - [LREM](https://redis.io/commands/lrem/)
- [x] featuredから消せる？ - [ZREM](https://redis.io/commands/zrem/)

**Comment by Sayamame-beans** [comment]
>  Home noteがPublic RNされてるって状態になりえそうだけどこれどう処理する? Recursiveに処理するの大変そう
>  同リプライ

その後の処理で不整合が起きないなら(起きなさそう)、そのまま置いておいて良い気がしたり…?
モデレーション機能なので、その他のノート(リプ/引用RN)が対象になるならそのノートも同様に処理対象(≒手動で問題なさそう)のはず…
RNについては、(原理上はAPIとかで可能そうですけど)RNをRNすることは通常無いので良いんじゃないですかね

>  ほかサーバ(含リレー)に非homeとして配信されてるのはまぁ放置するしかないけどOK?

良いと思います。
画像の閲覧注意変更も連合されてないのに…というのもありますし、相手に届いている以上はある程度相手側の管轄になりそうというのもあります。(実際、こちらは逆のこと…相手のpublicノートをhome化することが出来るようになるわけですし。)

**Comment by anatawa12** [comment]
もとpublicなnoteのPublic RNってhomeに変えて欲しいってことになる？

**Comment by Sayamame-beans** [comment]
> もとpublicなnoteのPublic RNってhomeに変えて欲しいってことになる？

そう…なりますね?
homeに切り換えて以降であれば、API的に(確かbackにあったと思うのですけれど)リプライ/RNの範囲制約が掛かるので、自動的にhome以下になる…というかpublicでは出来ないのが自然かなと思います。
もちろん、他のサーバーでは別です。あくまでhomeに切り換えたことが認識されているサーバー…すなわち、当該モデレーション操作が行われたサーバーが対象の話になりますね。(現状のサイレンスはそういう挙動をしているはずですし…)

**Comment by anatawa12** [comment]
では少なくともシンプルRNは切り替えるようにします。

**Comment by Sayamame-beans** [comment]
> Push TLになったあとのTLから消した方がいい？(消さないほうが楽)

どういう形になるかイメージ付いてないです。
public(LTL/GTL)からは消した方が良さそうな気もしますけど…(STLって内部的にどうなるんでしょう)
HTLは大丈夫そう。(確かnoteIdしか入ってないって先日聞いたような…?)

>  各種public only featuredの候補から消した方がいい？(消さないほうが楽)

あー…となっています。(public only featured…どのくらいあったっけ)

**Comment by anatawa12** [comment]
STLはHTLとLTLの合成なので仕様考えるときはあんま考慮しないでいい認識でいます。
GTLはそもそも遡れなくなるのでまぁ無視。で残るがLTLなので消す？ってなった感じ

featured、ローカルの投稿featuredが一番大きいかと思う

**Comment by Sayamame-beans** [comment]
> STLはHTLとLTLの合成なので

それはそう…配信されるデータが配信時に合成されるものなら気にする要素は無さそう。

> GTLはそもそも遡れなくなるのでまぁ無視。で残るがLTLなので消す？ってなった感じ

ふーむ、なるほど…遡れなくなる…
LTLはまあ、消した方が良いかな〜とは思うのです。LTLだけならノートの削除処理の一部と大差ない動き(RedisなLTLから除く?)で終わりそう…?という素人考えがあるのと、消えなかったらあんまりモデレーションとして意味ないよねという感じがありますが、実装が面倒なら悩みものですね。
 
> featured、ローカルの投稿featuredが一番大きいかと思う

あー、ハイライト…

**Comment by Sayamame-beans** [comment]
ハイライト、当該モデレーション時点で入っていた場合の話だと思っているのですが、あってます…? (原理がポイント式っぽいことしか知ってないので、どう影響するか分かってません)

あってるとして、ハイライトに入るようなのが対象ならhome化モデレーションではなく削除モデレーション対応をすれば良いという可能性は感じます。
あってない場合、home化した後にハイライトに入ってきたら(前述同様)意味なくなりそうという感じがあります。

**Comment by Sayamame-beans** [comment]
原文にあった"featuredの候補"という言葉を読み落としてました()
home化した後にハイライトに入ってきたら(前述同様)モデレーションした意味がなくなりそうという感じがあります。
