### ISSUE TITLE
ハイライト(notes/featured)から、写真のないおはようノートとチャンネル投稿を除外する

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#8]
## Summary

https://misskey.niri.la/notes/9hgbftjahc
ハイライトがおはようノートで埋まってるのが気になっており、フィルタ出来ても良さそう。
ただ、文字列での指定では写真がある場合を例外に出来ない。(写真があるならハイライトに出ても良さそうなので)
なのでメディア有無も条件として設定出来たら良いかなと考えてみました。

関連:
https://github.com/misskey-dev/misskey/issues/6019
https://github.com/misskey-dev/misskey/issues/6050
https://github.com/misskey-dev/misskey/issues/6115

当該部分のソース(…?): https://github.com/niri-la/misskey.niri.la/blob/a80c60bdc5f96e1e06da88b3d4d19e8f5610b7fb/packages/backend/src/server/api/endpoints/notes/featured.ts

**Comment by Sayamame-beans** [comment]
チャンネル投稿を含まないようにもしたいかもしれない。

**Comment by Sayamame-beans** [comment]
後で本家にも投げてみますね

**Comment by Sayamame-beans** [comment]
投げました。

**Comment by anatawa12** [comment]
現状はハードコートで、本家の misskey-dev#11401 が実装され次第そっちに切り替える方向で

**Comment by Sayamame-beans** [comment]
CW(注釈)に対象が含まれている場合、textしか見ていないので取りこぼしているようです
どうしましょうか

**Comment by anatawa12** [comment]
普通にCW見ればいい気がするけどそれだと問題ある?

**Comment by Sayamame-beans** [comment]
> 普通にCW見ればいい気がするけどそれだと問題ある?

それで大丈夫だと思います(多分)
