### ISSUE TITLE
絵文字ピッカーにフォルダ階層の概念を取り入れる

### ISSUE THREAD

**Issue by meronmks** [niwaniwa/misskey#80]
## Summary
現状の「大分類/中分類」みたいな分類法だと第一階層がとんでもないことになるのでフォルダ分けが可能になると便利なのではという提案。

実装されようとしているサーバーがあるので動きは以下のノート参照
https://misskey.niri.la/notes/9kz2bsb10x

実装されてるであろうコミット
https://git.nanasi-apps.xyz/mattyatea/misskey/commit/a3743a06229b9111b9a38c9d4bbda6a93e9207ea
https://git.nanasi-apps.xyz/mattyatea/misskey/commit/81182b86120487e1ef2637f8139d4d2b504c0d3f

もしかしたらAPIの互換性とかでただただ引っ張ってくるではダメかもしれないけど参考にはなるはず。
（絵文字申請botとの兼ね合いもありますし・・・）

**Comment by meronmks** [comment]
ものは試しで自分ところでやってみた。
https://github.com/meronmks/misskey/pull/1/files

**Comment by meronmks** [comment]
本家に向けて発射したので向こうのレビューとかで洗練されてきたらこちらにも発射します。

https://github.com/misskey-dev/misskey/pull/12132

**Comment by anatawa12** [comment]
@meronmks https://github.com/misskey-dev/misskey/pull/12132 の現在の状態ってどんな感じです？シンプルにreviewまちであればsyuiroさんに@投げたほうがいいかもです & pickを検討します

**Comment by meronmks** [comment]
@anatawa12 シンプルにreview待ちだったので@投げてきました。

**Comment by meronmks** [comment]
#110 で取り込まれてるのでcloseしちゃいますね

**Comment by Sayamame-beans** [comment]
今気付いたんですけど、その他/*がある時は、タグ指定なしで発生する"その他"も一緒に突っ込んで欲しい感じもあるのかもしれない…
でも後者は多分使ってる言語で表記変わるんですよね。
悩ましい
