### ISSUE TITLE
fg.colorとbg.colorを8桁RRGGBBAAに対応させたい

### ISSUE THREAD

**Issue by KisaragiEffective** [niwaniwa/misskey#86]
### Summary

upstream: https://github.com/misskey-dev/misskey/issues/10683

fg.colorとbg.colorはフロントエンド側で`/[0-9a-fA-F]{3,6}/i`としてフィルタがかけられているが、CSSの&lt;hex-color&gt; ([MDN](https://developer.mozilla.org/ja/docs/Web/CSS/hex-color)) は3桁、4桁、6桁に加えて8桁を許容するため

### Purpose

https://github.com/misskey-dev/misskey/blob/95095ee8d11a07938c183d4391de0a76ade31d44/packages/frontend/src/components/global/MkMisskeyFlavoredMarkdown.ts#L232C27-L232C27 の正規表現を`/^[0-9a-f]{3,4}([0-9a-f]{2}|[0-9a-f]{4})?$/`にする (5桁を許容しなくなるというbreaking changeが発生するが、現行バージョンでは色がつかず何かがおかしいと気がつくはずなので実質breaking changeではない)

**Comment by KisaragiEffective** [comment]
本家にPRを送ってレビュー待ち状態なのでこっちは閉じます

**Comment by KisaragiEffective** [comment]
本家PRが1か月ほど放置されてマージされる見込みがないので、連合なしノートに限ってこの機能を実装するか検討しています

**Comment by anatawa12** [comment]
独自ではやらない
