### ISSUE TITLE
次pickしたいやつを載せていくやつ

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#89]
https://github.com/misskey-dev/misskey/pull/12416 (CHANGELOGに記載されていない点に注意が必要)

**Comment by Sayamame-beans** [comment]
https://github.com/misskey-dev/misskey/pull/12433
https://github.com/misskey-dev/misskey/pull/12368

**Comment by anatawa12** [comment]
12433はOK

12368は https://github.com/misskey-dev/misskey/pull/12368#issuecomment-1820702014 がきになる

**Comment by anatawa12** [comment]
気になりはしたけどぱっと見該当commitなさそうなのでいいや。入れちゃう
