### ISSUE TITLE
絵文字入力時のサジェストがおかしい

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#94]
### 💡 Summary

例えばonigiri (入力過程で出るときと、一度閉じて後ろの部分だけ弄って再度出したときでも動きが違うので、こっちの挙動は重複の省き忘れとか?)
![image](https://github.com/niri-la/misskey.niri.la/assets/61457993/df860da3-5a0a-464c-b783-faf810f98788)
他には
> :goku: がサジェストに出てこない

https://misskey.niri.la/notes/9mjy7494mp
https://misskey.niri.la/notes/9mjy7qh0mx
> ローマ字でも出てこないね、アプデ後から

https://misskey.niri.la/notes/9mjya330nm
> リアクションピッカーには出てくるからバグっぽそう
https://misskey.niri.la/notes/9mjyanc68z

こっちの挙動は多分別…?

### 🥰 Expected Behavior

絵文字ピッカーと同じように候補が出る

### 🤬 Actual Behavior

重複したり、出ない候補があったりする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by anatawa12** [comment]
might related: misskey-dev#12365

**Comment by anatawa12** [comment]
da30643 (MisskeyIO#261)がむこうの方に入ってるからこれをpickすれば良さそう。
