### ISSUE TITLE
ハイライトにミュートが適用されない

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/misskey#96]
### 💡 Summary

> featuredのユーザミュート、思ったよりみんなほしいと思ってる？(ユーザミューとしたいと思ったことがない人間なので感覚がわかってない)

https://misskey.niri.la/notes/9mk60n9wze

> ミュートしたい理由を考えると、それはつまり見たくない/見えたら嫌だからであるので、見えるのは困る

https://misskey.niri.la/notes/9mk634yrdx
等

ref: https://github.com/misskey-dev/misskey/issues/12383 ?

### 🥰 Expected Behavior

ミュートが適用される

### 🤬 Actual Behavior

ミュートが適用されない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Sayamame-beans** [comment]
-off topic-
このissue書いてて思ったけど、個別サーバーのリポジトリなのにserver urlとmisskey version聞くの不毛そう
backendは尚更

**Comment by anatawa12** [comment]
それはそうなんだけど、面倒でissue template作り直してない。やってくれるならmergeします

**Comment by Sayamame-beans** [comment]
> ハイライトのユーザミュートの件、修正したとあるけど機能してにゃい疑惑…？
> ハイライト＝「みつける」についてユーザミュートが機能していないように見受けられます...。
https://misskey.niri.la/notes/9mlab2cwn8

**Comment by Sayamame-beans** [comment]
機能していないことを確認
調査中です

**Comment by anatawa12** [comment]
どっちのfeaturedで確認されてます？

**Comment by Sayamame-beans** [comment]
全体ハイライトですね
個人単位のは見るの忘れてました

**Comment by Sayamame-beans** [comment]
個人単位、少なくとも引用先のユーザーがミュート対象のケースで機能して無さそうでした

**Comment by anatawa12** [comment]
ミュート追加直後だと機能しないという仕様ありますがそういう話でもないですよね...確認します

**Comment by Sayamame-beans** [comment]
あ～…私が試したのは追加して数分以内の話なので、それに入っちゃってるかもしれません
(10分期限のミュートを掛けて試してました)

**Comment by Sayamame-beans** [comment]
「引用は消えるけど本人のは消えない」挙動かも

**Comment by Sayamame-beans** [comment]
ignoreAuthor = trueが原因かも
